services:

  postgres:
    image: postgres:18
    container_name: task-manager-postgres
    environment:
      POSTGRES_DB: task_manager
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"

  api:
    image: task-manager-api:latest
    container_name: task-manager-api
    depends_on:
      - postgres
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/task_manager
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
    ports:
      - "8080:8080"